/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistausuario;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Joshua
 */
public class VistaCreditos extends javax.swing.JFrame {
    DefaultTableMode1 modelo;
    

    /**
     * Creates new form CreditoHipotecario
     */
    public VistaCreditos() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //modelo=new DefaultTableMode1();
        
        //Metodo para agregar columnas a la tabla
        /*this.TablaDeDetalles.setModel(modelo);
        this.modelo.addColumn("No.de cuota");
        this.modelo.addColumn("Monto cuota");
        this.modelo.addColumn("Interes");
        this.modelo.addColumn("Amortización");
        this.modelo.addColumn("Deuda");*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TipoCredito = new javax.swing.JComboBox<>();
        Plazos = new javax.swing.JComboBox<>();
        Monto = new javax.swing.JTextField();
        Cedula = new javax.swing.JTextField();
        BotonColones = new javax.swing.JRadioButton();
        BotonDolares = new javax.swing.JRadioButton();
        Generar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDeDetalles = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1.setText("Registro de crédito");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 150, 25));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 238, 25));

        TipoCredito.setBackground(new java.awt.Color(51, 51, 51));
        TipoCredito.setForeground(new java.awt.Color(102, 102, 102));
        TipoCredito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hipotecario de terreno", "Hipotecario de vivienda", "Fiduciario", "Prendario", "Personal" }));
        jPanel1.add(TipoCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, 30));

        Plazos.setBackground(new java.awt.Color(51, 51, 51));
        Plazos.setForeground(new java.awt.Color(102, 102, 102));
        Plazos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 año", "2 años", "3 años", "4 años", "5 años", "6 años", "7 años", "8 años", "9 años", "10 años", "11 años", "12 años", "13 años", "14 años", "15 años" }));
        jPanel1.add(Plazos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, 30));

        Monto.setBackground(new java.awt.Color(51, 51, 51));
        Monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MontoKeyTyped(evt);
            }
        });
        jPanel1.add(Monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, 30));

        Cedula.setBackground(new java.awt.Color(51, 51, 51));
        Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CedulaKeyTyped(evt);
            }
        });
        jPanel1.add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 200, 30));

        BotonColones.setBackground(new java.awt.Color(51, 51, 51));
        BotonColones.setText("Colones");
        BotonColones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonColonesActionPerformed(evt);
            }
        });
        jPanel1.add(BotonColones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, 30));

        BotonDolares.setBackground(new java.awt.Color(51, 51, 51));
        BotonDolares.setText("Dolares");
        jPanel1.add(BotonDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 200, 30));

        Generar.setBackground(new java.awt.Color(51, 51, 51));
        Generar.setText("Generar");
        jPanel1.add(Generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 540, -1, -1));

        jLabel2.setText("Tipo de crédito");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, 30));

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 540, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 575));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaDeDetalles.setBackground(new java.awt.Color(0, 0, 0));
        TablaDeDetalles.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(TablaDeDetalles);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 520, 449));

        jButton1.setText("Limpiar");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 580, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonColonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonColonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonColonesActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        
        Menu newframe = new Menu();
        
        newframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedulaKeyTyped
        // TODO add your handling code here:
        
        char validar=evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solamente números");
        }
    }//GEN-LAST:event_CedulaKeyTyped

    private void MontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        
        if (((caracter < '0' || caracter > '9'))
                &&(caracter != KeyEvent.VK_BACK_SPACE)
                &&(caracter != '.' || Monto.getText().contains("."))
                 &&(caracter != ',' || Monto.getText().contains(","))){
            
            evt.consume();
            
        }
    }//GEN-LAST:event_MontoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCreditos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotonColones;
    private javax.swing.JRadioButton BotonDolares;
    private javax.swing.JTextField Cedula;
    private javax.swing.JButton Generar;
    private javax.swing.JTextField Monto;
    private javax.swing.JComboBox<String> Plazos;
    private javax.swing.JButton Regresar;
    private javax.swing.JTable TablaDeDetalles;
    private javax.swing.JComboBox<String> TipoCredito;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
